---
_hotel_id: COU198
_portal_id: required-but-empty
_root_path: https://qa5.ttaws.com/rt
latitude: 43.04593
longitude: -89.32486
name: Country Inn & Suites By Carlson Madison
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: 400 River Pl
  street2: ''
  state: Wisconsin
  city: Madison
  country: United States
  zip_code: '53716'
